### ISSUE TITLE
XBRL Conversion Started

### ISSUE THREAD

**Issue by bbkrr** [janlukasschroeder/sec-api#30]
While using the `xbrl_to_json` api I am getting an error `{'message': 'XBRL conversion started, but the processing has not been completed. Please try again after 60 seconds.'}`. Some days before I was able to fetch the records for the same xbrl but now it is showing the error. Also, it is showing such issue for most of the companies.

xbrl url: `https://www.sec.gov/ix?doc=/Archives/edgar/data/0001039828/000103982821000018/ael-20201231.htm`

Note: Even though the messages says to try again after 60 seconds, it does not work. It's been more than a week, I am getting this error.

Regards.

**Comment by janlukasschroeder** [comment]
@bbkrr thanks for bringing this to our attention. 

Let's start by addressing the HTTP 202 reponse `{'message': 'XBRL conversion started, but the processing has not been completed. Please try again after 60 seconds.'}`. The response indicates that our system didn't find the converted JSON version of the XBRL data in our distirbuted caching system and triggered a new conversion. The distributed caching system is new and was recently launched. The old infrastructure handeled this case differently and that's why you saw such messages starting to appear just recently. 

Having said this, you actually should only see the 202 message when accessing filings younger than 1 second. For older messages, the new caching infrastructure should send the usual response. And that's where you discovered an edge case. The new caching system didn't handle CIKs with leading zeros in the URL (e.g. `0001039828`). It worked for all URLs with no-zero padding (e.g. `1039828`). We just released a fix and both cases work as usual now.
