### ISSUE TITLE
Exact match for name does not work in a mapping call

### ISSUE THREAD

**Issue by volgin** [janlukasschroeder/sec-api#5]
'https://mapping-api.herokuapp.com/name/%5Etesla$'
does not work, while
'https://mapping-api.herokuapp.com/ticker/%5Etsla$'
does.

**Comment by janlukasschroeder** [comment]
@volgin that's actually the correct behaviour. You're using regex on the `name` endpoint, ie only companies with the exact name `tesla` are returned. The result is empty because there is no company with such a name. 

In regex, the `$` denotes the end of the string. Try https://mapping-api.herokuapp.com/name/%5Etesla and it works :)

**Comment by volgin** [comment]
Good point. It would be nice to be able to retrieve "Apple Inc" for "Apple", but not "Applebees", but I guess I should implement this logic on my end. Do you support full regex syntax, or only ^ and $?

**Comment by janlukasschroeder** [comment]
> It would be nice to be able to retrieve "Apple Inc" for "Apple", but not "Applebees"

For this use case you can use the ticker endpoint
https://mapping-api.herokuapp.com/ticker/aapl

Let me know if you have other use cases similar to this one and I'm happy to work through patterns and develop something that solves your use cases.

> Do you support full regex syntax, or only ^ and $?

Yes, full regex support provided. The JavaScript regex function below is used on the backend. [See here for supported syntax and regex engines.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)

```js
const regex = RegExp(value, 'ig');
```
